version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redisdata:/data"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgresdata:
  # redisdata:
